---
- name: install required RPMs
  package:
    name: "{{item}}"
    state: present
  become: yes
  with_items: "{{required_rpms}}"

- name: set static ip with network manager
  shell: |
    nmcli dev mod eth1 ipv4.method manual ipv4.addr "{{pxe_server_ip_addr}}"
  become: yes

- name: modify configuration file of dhcp server
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  become: yes

- name: start and enable dhcpd service
  service:
    name: dhcpd
    enabled: yes
    state: started
  become: true

- name: start and enable tftp socket
  service:
    name: tftp.socket
    enabled: yes
    state: started
  become: true

- lineinfile:
    path: /etc/vsftpd/vsftpd.conf
    state: present
    regexp: '^anonymous_enable'
    line: 'anonymous_enable=YES'
  become: true

- name: start and enable vsftpd service
  service:
    name: vsftpd
    enabled: yes
    state: started
  become: true

- name: download minimal installation iso image to localhost
  get_url:
    url: "{{iso_img_url}}"
    dest: "vagrant_data/{{iso_img_file}}"
    checksum: "{{iso_img_checksum}}"
  delegate_to: localhost

- name: create directory /vagrant_data
  file:
    path: /vagrant_data
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755
  become: true

- name: copy iso image to pxe server
  copy:
    src: "vagrant_data/{{iso_img_file}}"
    dest: "/vagrant_data/{{iso_img_file}}"
  become: true

- name: mount iso image
  mount:
    src: "/vagrant_data/{{iso_img_file}}"
    path: "{{iso_img_mount_path}}"
    fstype: "iso9660"
    opts: ro
    state: mounted
  become: true

- name: rsync content of iso image with /var/ftp/pub
  shell: "rsync -a {{iso_img_mount_path}}/ /var/ftp/pub"
  become: true

- name: unmount iso image
  mount:
    path: "{{iso_img_mount_path}}"
    state: unmounted
  become: true

- name: create directory /var/lib/tftpboot/pxelinux.cfg
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
    mode: 0755
  become: true

- name: create directory /var/lib/tftpboot/netboot
  file:
    path: /var/lib/tftpboot/netboot
    state: directory
    mode: 0755
  become: true

- name: copy syslinux files to /var/lib/tftpboot
  copy:
    src: "/usr/share/syslinux/{{item}}"
    remote_src: yes
    dest: /var/lib/tftpboot
  with_items: "{{syslinux_files}}"
  become: true

- name: copy pxeboot kernel files to /var/lib/tftpboot/netboot
  copy:
    src: "/var/ftp/pub/images/pxeboot/{{item}}"
    remote_src: yes
    dest: /var/lib/tftpboot/netboot
  with_items: "{{kernel_files}}"
  become: true

- name: stop service for automatic building of updates.img
  service:
    name: autobuild_updates_img
    state: stopped
  become: true

- name: create updates.img file
  command: "./scripts/build_updates_img.sh --python python3"
  args:
    chdir: "/vagrant"

- name: copy updates.img to pxe server
  copy:
    src: /vagrant/updates.img
    remote_src: yes
    dest: /var/ftp/pub/updates.img
  become: true

- name: create service for automatic building of updates.img
  copy:
    src: autobuild_updates_img.service
    dest: "{{systemd_service_dir}}"
  become: yes

- name: enable and start service for automatic building of updates.img
  service:
    name: autobuild_updates_img
    enabled: yes
    state: started
  become: true

- name: create default file containing boot menu
  template:
    src: default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/default
  become: true

- name: create kickstart file
  template:
    src: "ks_{{distro_name}}{{distro_version}}.cfg.j2"
    dest: /var/ftp/pub/ks.cfg
  become: true

- name: disable SELinux
  shell: "setenforce 0"
  become: true